## https://taplo.tamasfe.dev/configuration/file.html

exclude = [".idea/**", "bin/**", "build/**", "contrib/**", "dist/**"]

[formatting]
array_auto_collapse = false
indent_string = '    '
reorder_keys = false
allowed_blank_lines = 1
